services:
  postgres:
    container_name: PetFamily.Postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: pet_family
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: galaxy
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  seq:
    container_name: PetFamily.Seq
    image: datalust/seq:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
  
  minio:
    container_name: PetFamily.Minio
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  postgres-data:
  minio_data:
